### PR TITLE
Heppy - recover original MT2 precision

### PR DESCRIPTION
**Pull request by brucala**
title says it all

### CODE REVIEW

**Comment by gpetruc** [comment]
does it make any significant difference in the timing?
@mariadalfonso

**Comment by pandolf** [comment]
hi guys

just to inform you that while it would be indeed interesting to see if this affects timing, we don't really have a choice: this is a bug that was introduced in november in heppy [1], of which we were not aware, and we need to go back to the previous value for syncronization reasons.

ciao
f

[1]: as you can see here:

https://github.com/CERN-PH-CMG/cmg-cmssw/commi/908095816aa7214b8e9b143cb7f365600b2e0d59

when moving the parameter from Davismt2.h and mt2w_bisect.h to Davismt2.cc and mt2w_bisect.cc a zero was "lost"

**Comment by pandolf** [comment]
sorry, missing t in the link:

https://github.com/CERN-PH-CMG/cmg-cmssw/commit/908095816aa7214b8e9b143cb7f365600b2e0d59

**Comment by gpetruc** [comment]
I see, maybe next time write this more clearly in the description of the PR?

Also, why don't you fix also the other file then?

**Comment by mariadalfonso** [comment]
@gpetruc 
the module ttHTopoVarAnalyzer that call this class it account only for 1% of the overall time in the run_susyMT2_cfg.py sequence 
So with Bruno fix, the picture doesn't change

**Comment by gpetruc** [comment]
Ok, so I'll just wait for the  fix also in `mt2w_bisect` and then merge the branch

**Comment by pandolf** [comment]
@brucala can you do this?

**Comment by brucala** [comment]
done

**Pull request merged**
