### PR TITLE
More gen jet options and matched gen info for leptons and photons

### PR DESCRIPTION
**Pull request by aelwood**
Added option to Jet Analyzer that allows gen jets to be cleaned from reco photons.

Added matched mcPt information into the tree for leptons and photons in a way analogous to jets.

Fixed problem with the alphaT variable analyzer after the RootTools cleanup

Make HT, MHT and alphaT from gen jets as well.

### CODE REVIEW

**Comment by pandolf** [comment]
hi @aelwood 

did you check if the new variables computed by default on genjets (ht/mht 40/50) slow down the processing time?

https://github.com/CERN-PH-CMG/cmg-cmssw/pull/310/files#diff-2

**Comment by gpetruc** [comment]
Hi,

Is there a reason you closed it?
Are you going to make a new one?

**Comment by aelwood** [comment]
Sorry, some branch renaming shenanigans caused it to be automatically closed. I've remade it here : 
https://github.com/CERN-PH-CMG/cmg-cmssw/pull/313

**Comment by aelwood** [comment]
@pandolf I tested the timing:

The ttHCoreEventAnalyzer went from taking 7.7% of the time to 7.8% of the time. I presume this can be counted as a negligible increase?

**Pull request closed without merging**
