### PR TITLE
Merge of Colin's 7_4_5 into CMGTools

### PR DESCRIPTION
**Pull request by gpetruc**
Like #419 but with a few extra updates needed on the CMGTools side:
- be26bc4 : susyCore_modules_cff: Change default JECs from PHYS14_25_V2 to Summer15_V5_MC
- e830f14 : Adapt cfgs to the upstream change framework.heppy -> framework.heppy_loop

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@gpetruc For me can be merged, 
out of 10k we get identical results between PF420 and what is in the release now
http://dalfonso.web.cern.ch/dalfonso/validationPR42010k/

**Comment by steggema** [comment]
@gpetruc Fine for me as well - gives identical results for tau-tau, also if using 746 as base release.

**Comment by gpetruc** [comment]
Ok. Myself, i was testing it in 7_4_6_patch6 but there i get crashes
(segmentation violation) when Heppy is run multithread, that i still don't
understand: the crash happens only after some events, and it appears even
running the plain heppy example_autofill cfg (if one sets splitFactor > 1).
It was not happening in 7_4_3

Il 8-lug-2015 09:55, "Jan Steggemann" notifications@github.com ha scritto:

**Comment by steggema** [comment]
It's probably unrelated, but I get post-execution seg faults when importing cx_Oracle in the same python config as heppy - as is our default in tau-tau - and it looks like some multithreading issue (but it's got nothing to do with heppy since it can be reproduced in 4 lines of pyfwlite)

**Comment by cbernet** [comment]
Hi Guys, 

I understand you guys want to move to 7_4_6_patch6. 
Good choice, you’ll be able to enjoy the new ipython :-) 
So I’m now porting the heppy developments to heppy_7_4_6_patch6. 

I have tested PhysicsTools/Heppy/test/simple_example_cfg.py in multiprocessing mode, 
it works. I intend to carry on more detailed tests this afternoon, to make sure the whole batch processing system is working.  

Cheers, 

Colin

**Comment by gpetruc** [comment]
Hi Colin,

In fact, what I see is that I get a segmentation violation if I run
multithreaded in ipython, and not if I run multithreaded in plain python.
So, I "enjoy" is not the word I'd use for the new ipython yet.
To reproduce the crash, on 7_4_6_patch6, taking the branch
CMGTools-from-CMSSW_7_4_X from my fork (
https://github.com/gpetruc/cmg-cmssw/tree/CMGTools-from-CMSSW_7_4_X ), and
going under CMGTools/TTHAnalysis/cfg
  python $CMSSW_BASE/src/PhysicsTools/HeppyCore/scripts/heppy_loop.py Trash
run_susyMultilepton_cfg.py -p 0 -o nofetch -o test=74X-MC -o sample=TT
         --> works
  ipython --pdb --
$CMSSW_BASE/src/PhysicsTools/HeppyCore/scripts/heppy_loop.py iTrash
run_susyMultilepton_cfg.py -p 0 -o nofetch -o test=74X-MC -o sample=TT
         --> segmentation violation after a few hundred events are
processed in each thread

Ciao,

  Giovanni

**Comment by gpetruc** [comment]
And, the crash really comes from the new ipython 3, because if I change in
PYTHONPATH the ipython from 3.1.0-odfocd to the older 0.10-cms and run
/cvmfs/
cms.cern.ch/slc6_amd64_gcc491/external/py2-ipython/0.10-cms/bin/ipython
--pdb -- $CMSSW_BASE/src/PhysicsTools/HeppyCore/scripts/heppy_loop.py
iTrash010 run_susyMultilepton_cfg.py -p 0 -o nofetch -o test=74X-MC -o
sample=TT things again don't crash.

**Comment by cbernet** [comment]
Hi Giovanni, 

Please note that my tests have been done with heppy (and thus ipython, not python).
Can you maybe try to run simple_example_cfg.py and let us know what happens? 
As Jan was pointing out, the problem might not be related to heppy, but to some code that is running in 
run_susyMultilepton_cfg.py 

Cheers, 

Colin

**Comment by gpetruc** [comment]
Hi Colin,

I used that as an example because that cfg is running multithreaded and
crashing out of the box, while to get example_autofill to segfault I need
to modify it so that the component is split etc.
The matrix of my tests is:
- heppy single-threaded, ipython 3: works
- heppy multi-threaded, python: works
- heppy multi-threaded, ipython 0.10: works
- heppy multi-threaded, ipython 3: fails

Ciao,

```
 Giovanni
```

**Comment by cbernet** [comment]
What I meant is that simple_example_cfg.py — not example_autofill — is multithreaded (splitFactor is set to 2 by default), 
and it does not crash. I was wondering whether it works for you or not. 
Can you try? 
You’re saying that the crash occurs after a few hundred events, right? 
If simple_example_cfg.py is working for you, then I can try to run it on more events. 
Let me know. 

Colin

**Comment by steggema** [comment]
Just to note that I can reproduce the crash in 7_4_6_patch6 with the heppy autofill example (with sample.splitFactor = 4 and sample.fineSplitFactor = 2).

The same works in 7_4_6, which already has ipython 3.1.0 (*).

I would guess that the other issue with importing cx_Oracle is unrelated because this crash goes away when running multithreaded (!) - though it still points to some more general issue with multithreading.

(*)  <module 'IPython' from '/afs/cern.ch/cms/slc6_amd64_gcc491/external/py2-ipython/3.1.0-odfocd/lib/python2.7/site-packages/IPython/__init__.pyc'>

**Comment by gpetruc** [comment]
Hi Jan,

I do get a crash also in plain 746. However, it seems to be something like
a race condition; if I take example_autofill with splitFactor 2 (as in
https://github.com/gpetruc/cmssw/commits/crash-74x-heppy ) and run, for a
while it's processing events only in one thread and things look fine, then
when the second thread has done some hundred events it finally crashes.
It could be that just running on a different machine or at a different time
may cause the crash to happen or not.
I don't get the crash in simple_example, but maybe that one completes to
quickly to run in the race?
Now I'm trying on more events, to see whether maybe on more events it
crashes also with plain python.

```
Giovanni
```

**Comment by cbernet** [comment]
In the meanwhile I will try to get simple_example to crash with more events. 

C

**Comment by cbernet** [comment]
No way to get the guy crash. I just processed 100 relval files in two chunks for a total of 1.5 million events :-/ 
I’m leaving now for vacation, unfortunately. 
I hope you will soon find the reason for this problem. 

Good luck! 

Colin

**Comment by gpetruc** [comment]
Executive proposal: for the moment, in the CMGTools branch I create two
binaries, "heppy" (runs python) and "iheppy" (runs ipython).
After all, ipython is mostly useful for when one wants to debug, and in
those cases one typically wants to run one job anyway, while when running
multi-threaded locally one usually just wants to get the output files and
doesn't care whether we're running in python or ipython.
This way we can merge the pull request and move to 746patch6
Once we sort out the problem, we go back to normal (heppy runs ipython).
Objections?

   Giovanni

**Comment by cbernet** [comment]
good idea
c

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Giovanni Petrucciani notifications@github.com
Date : 09/07/2015 18:03 (GMT+01:00)
À : CERN-PH-CMG/cmg-cmssw cmg-cmssw@noreply.github.com
Cc : Colin Bernet Colin.Bernet@cern.ch
Objet : Re: [cmg-cmssw] Merge of Colin's 7_4_5 into CMGTools (#420)

Executive proposal: for the moment, in the CMGTools branch I create two
binaries, "heppy" (runs python) and "iheppy" (runs ipython).
After all, ipython is mostly useful for when one wants to debug, and in
those cases one typically wants to run one job anyway, while when running
multi-threaded locally one usually just wants to get the output files and
doesn't care whether we're running in python or ipython.
This way we can merge the pull request and move to 746patch6
Once we sort out the problem, we go back to normal (heppy runs ipython).
Objections?

Giovanni

**Pull request merged**
