### PR TITLE
VV plotting update

### PR DESCRIPTION
**Pull request by mtosi**
add ratio plot and fix CMS text

### CODE REVIEW

**Comment by gpetruc** [comment]
@bachtis do you want to review the PRs on the VV subsystem?

**Comment by bachtis** [comment]
Hi @gpetruc . In fact , now that we are more than one in the VV subsystem I would like to merge . But we talk with Mia so no need to do +1s . Let me know if I can accept merges that are independent of other packages

**Comment by mtosi** [comment]
ciao
I've just committed the update
we have 2 distinct functions, now
drawStack and drawStackAndRatio

the latter is the new one w/ both stack and ratio
the former is almost the same as the original one

**Comment by gpetruc** [comment]
Ok. 

Mike, now you have merge rights. 

If it's something that affects **only** VV, you can go ahead and merge.
If it's something that affects both VV and something else (e.g. if there are Heppy commits), I would also check the things before, so wait for a message from me before merging.

**Comment by bachtis** [comment]
ok! thanks

**Pull request merged**
