### PR TITLE
Heppy - Replaced PAT photon isolation with RECO isolation

### PR DESCRIPTION
**Pull request by mmasciov**

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@aelwood This PR change the content to the photon isolation (isolation taken from RECO and not PAT now). Please double check.

**Comment by aelwood** [comment]
@mariadalfonso the code looks fine to me. As far as I can see it just adds an extra recoIsolation attribute rather than changing it?

**Comment by pandolf** [comment]
@aelwood be careful: the branches are overwritten here:

https://github.com/CERN-PH-CMG/cmg-cmssw/pull/234/files#diff-0

**Comment by aelwood** [comment]
@pandolf Ah right ok I see. All looks good to me then.

**Pull request merged**
