### PR TITLE
Updates to the ttHAnalysis framework from the RA1 SUSY group (alphaT)

### PR DESCRIPTION
**Pull request by aelwood**
Added control region variables for the AlphaT analysis to ttHAlphaTControlAnalyzer

Added an optional met with no muons to ttHMetAnalyzer

Added biased delta Phi to the ttHCoreEventAnalyzer

Added general purpose object skimmer: ttHObjectSkimmer. This takes the type of object to skim as a parameter, along with the name of the folder to be made by the skimmer in the output.

Added ttHIsoTrackSkimmer that skims on isolated tracks. There are also options to check if the isolated tracks are those from a muon or electron, and ignore these when skimming.

Added to the ttHGenEventAnalyzer the variables used for binning when generating events. E.g. the PtHat value or QScale. This is used for validation of the MC reweighting.

Added the option to put bools in the tree defined in Tree.py

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@aelwood @gpetruc 
Ciao Adam.
The fix for GJets sample https://github.com/CERN-PH-CMG/cmg-cmssw/pull/145/files#diff-9ac9a6b7e04037a1f85c722c08b4ef69L74 was already introduced in the PR#142.
Can you updated to solve the conflict ?

Maria

**Comment by aelwood** [comment]
@mariadalfonso 
Ciao Maria.
I've merged the latest update, which included that PR, and resolved the conflict. 
Cheers,
Adam

**Comment by gpetruc** [comment]
I have merged the PR as it was ok both for @mariadalfonso and for the multilepton, however I see that your own run_susyAlphaT_cfg.py doesn't seem to run properly (unfortunately I had spotted this only after merging, but you can fix it in a future pull request since anyway it doesn't harm the other groups; I'll leave a "bug" flag on this PR so we remember it).

```
[..]/python/analyzers/treeProducerSusyAlphaT.py in <lambda>(ev)
     47             # control sample variables
     48             ##--------------------------------------------------
---> 49             NTupleVariable("mtw", lambda ev: ev.mtw, help="mt(l,met)"),
     50             NTupleVariable("mtwTau", lambda ev: ev.mtwTau, help="mt(tau,met)"),
     51             NTupleVariable("IsoTrack_mtw", lambda ev: ev.mtwIsoTrack, help="mt(isoTrack,met)"),

AttributeError: 'Event' object has no attribute 'mtw'
```

**Comment by aelwood** [comment]
@gpetruc 
I omitted the latest version of run_susyAlphaT_cfg.py as we are still carrying out significant development on it. I hadn't realised the old version had stopped running, but I can fix this in a later PR. As you say, this shouldn't affect anyone else anyway.

**Pull request merged**
