### PR TITLE
rerunning MVA tau isolation in heppy

### PR DESCRIPTION
**Pull request by GaelTouquet**
- cross-checked to have the same isolation scores and WP as following the CMSSW recipe given here https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePFTauID#Rerunning_of_the_tau_ID_on_M_AN1 .
- isolation perfectly synchronised with other groups for the 2017 HTT anaylsis.

### CODE REVIEW

**Comment by GaelTouquet** [comment]
This development was done with @cbernet and @steggema .

**Comment by gpetruc** [comment]
looks like it conflicts even if contains the same commits cherry-picked from steggema.
can you rebase removing them, or fix the conflict otherwise?

**Comment by GaelTouquet** [comment]
Hello, we have fixed the conflicts that came from parallel developments with #736 . We have tested the latest version and have found a perfect agreement with other 2017 HTT analysis groups.

**Comment by cbernet** [comment]
@gpetruc could we merge?

**Comment by gpetruc** [comment]
I was waiting for @peruzzim to also test

**Pull request merged**
