### PR TITLE
Heppy: implement the RAZOR megajets

### PR DESCRIPTION
**Pull request by emanueledimarco**
A class to calculate the RAZOR megajet implemented, and methods to choose the best combination.

### CODE REVIEW

**Comment by gpetruc** [comment]
Wouldn't it be cleaner for this and similar variables to have also constructors from vectors of LorentzVector, like we have in [ReclusterJets](https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_2_3/PhysicsTools/Heppy/interface/ReclusterJets.h#L25) ?
After all, python is not fortran 77 (even if they two share some sensitivity to whitespace).
Anyway, no objections at merging this for now.

**Comment by cbernet** [comment]
I would agree with Giovanni.

**Comment by gpetruc** [comment]
Hi @emanueledimarco: this PR was supposed to go into the heppy branch instead of CMGTools (the cmgtools one is #309). I'll close it, you can reopen it on the correct branch from [this link](https://github.com/CERN-PH-CMG/cmg-cmssw/compare/heppy_7_2_2_patch2...emanueledimarco:heppy_7_2_2_patch2_monox?w=1)

**Comment by emanueledimarco** [comment]
@gpetruc Sure. I was initially going to do so, but I wanted on purpose to maintain a syntax as close as possible to  https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_2_3/PhysicsTools/Heppy/interface/Hemisphere.h#L77

I can update the file adding more constuctors as you suggest

**Pull request closed without merging**
