### PR TITLE
Upstream Heppy updates

### PR DESCRIPTION
**Pull request by gpetruc**

### CODE REVIEW

**Comment by gpetruc** [comment]
@cbernet @arizzi are there any things still pending that I should wait for before trying to solve the conflicts and merge on our side?

**Comment by arizzi** [comment]
on our side we should figure what to do with cbernet/cmssw#43 that was closed but we actually merged it on vhbb side.. so in any case it has to be remade properly from scratch and conflict solved on our side... I guess you can go ahead as far as vhbb is concerned

**Comment by cbernet** [comment]
nope. a few pull requests on my side but nothing fancy. I can deal with that later.

Colin

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Giovanni Petrucciani notifications@github.com
Date : 26/08/2015 14:05 (GMT+01:00)
À : CERN-PH-CMG/cmg-cmssw cmg-cmssw@noreply.github.com
Cc : Colin Bernet Colin.Bernet@cern.ch
Objet : Re: [cmg-cmssw] Upstream Heppy updates (#497)

@cbernethttps://github.com/cbernet @arizzihttps://github.com/arizzi are there any things still pending that I should wait for before trying to solve the conflicts and merge on our side?

**Comment by gpetruc** [comment]
will force-update this PR from @cbernet's current 7_4_7_patch1 branch

**Comment by gpetruc** [comment]
Updated now.

People please test this with your configs.

**Comment by mariadalfonso** [comment]
@gpetruc 
This is transparent respect to the MT2 currently in release, you can merge from my side
https://dalfonso.web.cern.ch/dalfonso/validationPR497/plots/

These files are ahead in the CMG branch
https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_4_7/PhysicsTools/HeppyCore/scripts/heppy_loop.py#
https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_4_7/PhysicsTools/HeppyCore/scripts/heppy

**Pull request merged**
