### PR TITLE
Summer15_V5 JEC added

### PR DESCRIPTION
**Pull request by schoef**

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@schoef can you add the .db file as well ?

**Comment by artlbv** [comment]
Hi @schoef 
when I try to use those files (I patched my branch with this PR), I get a segmentation violation after:

``` bash
%MSG-e JetCorrectorParameters: 
No definitions found!!!
%MSG
%MSG-e JetCorrectorParameters: 
No definitions found!!!
%MSG
%MSG-e JetCorrectorParameters: 
No definitions found!!!
%MSG
Error in <TFormula::TFormula>: expression may not be 0 or have 0 length
Error in <TFormula::TFormula>: expression may not be 0 or have 0 length
Error in <TFormula::TFormula>: expression may not be 0 or have 0 length
...
```

The full error log is here: http://desy.de/~lobanov/SUSY/Run2/CMG/devel/summer15_jec_error.log
Is it a bug in the files, or did I apply them wrong?
I just set this to use them: `jetAna.mcGT = "Summer15_V5"`

thanks, artur

**Comment by mariadalfonso** [comment]
@artlbv 
it works with the full string 
jetAna.mcGT = "Summer15_V5_MC"

**Comment by artlbv** [comment]
@mariadalfonso thanks! I missed that part.

**Pull request merged**
