### PR TITLE
MonoXAnalysis developments

### PR DESCRIPTION
**Pull request by emanueledimarco**
- Including photon analyzer change to include conversion safe veto ( PR #578 )
- add analyzer to dump only isolated taus for vetoing them
- additions for the friend trees

### CODE REVIEW

**Comment by gpetruc** [comment]
@emanueledimarco : could you add the default also in https://github.com/CERN-PH-CMG/cmg-cmssw/blob/CMGTools-from-CMSSW_7_4_12/CMGTools/TTHAnalysis/python/analyzers/susyCore_modules_cff.py#L208-L218 please?

@mariadalfonso except for that the PR seems ok to me, but I don't have plots for photons in my validation suite

**Comment by emanueledimarco** [comment]
@gpetruc sure. Just done. 
@mariadalfonso I don't have plot neither, but I have done a synch for monojet and everything looks fine (with the conversion safe electron veto)

**Comment by emanueledimarco** [comment]
@mariadalfonso just making sure this is merged at some point (not to risk having conflicts if other pull requests mix to this). Thanks.

**Comment by mariadalfonso** [comment]
leave unchanged the default https://dalfonso.web.cern.ch/dalfonso/validationPR579TTbar10k/?match=gamma

**Pull request merged**
