### PR TITLE
ttH multilepton: updated charge flip measurements and closure tests

### PR DESCRIPTION
**Pull request by stiegerb**
- new lepton MVA training
- full 2015 lumi

### CODE REVIEW

**Comment by stiegerb** [comment]
Don't merge yet. I'm updating with the final selection.

**Comment by stiegerb** [comment]
Ok to merge from my side.

**Comment by gpetruc** [comment]
Merging for the record, even though now the analysis has been moved to 76X.
Was this feature already ported to 76X in Marco's branch?

**Comment by stiegerb** [comment]
Yes, this is included in Marco's `works_260116_76X` branch. See the corresponding PR on his repo here:
https://github.com/peruzzim/cmgtools-lite/pull/3

**Pull request merged**
