### PR TITLE
Electron / photon scale and resolution corrections for ICHEP 2016

### PR DESCRIPTION
**Pull request by emanueledimarco**
Implemented the corrections from https://twiki.cern.ch/twiki/bin/viewauth/CMS/EGMSmearer
To use them, you need to: 
- cd EgammaAnalysis/ElectronTools/data
- git clone -b ICHEP2016_approval_4fb https://github.com/ECALELFS/ScalesSmearings.git ; cd -
- scram b

To configure the corrections 
- electrons:
  
  lepAna.doElectronScaleCorrections = {
      'data' : 'EgammaAnalysis/ElectronTools/data/ScalesSmearings/80X_Golden22June_approval',  
      'GBRForest': ('$CMSSW_BASE/src/CMGTools/RootTools/data/egamma_epComb_GBRForest_76X.root',
                    'gedelectron_p4combination_'+era),
      'isSync': sync
  }
- photons:
  
  photonAna.doPhotonScaleCorrections = {
      'data' : 'EgammaAnalysis/ElectronTools/data/ScalesSmearings/80X_Golden22June_approval',
      'isSync': sync
  }

### CODE REVIEW

**Comment by schoef** [comment]
@emanueledimarco 

thanks a lot. era should be '25ns', sync should be False.
I sanity-tested the PR, change in pt for photon, electron is within expectation.

**Comment by emanueledimarco** [comment]
@schoef yes, sorry, I omitted the values for those parameters. They are like you say. 
I also tested it and it runs, but I am now running on full DoubleEG and SinglePhoton to make 
a more extensive validation (also because there were rare crashes)

**Comment by schoef** [comment]
@emanueledimarco 
OK, please let me know because I'm about to launch a full scale tupelization
Thanks for the heads-up

**Comment by emanueledimarco** [comment]
And this should also fix the other problem reported by Philipp, i.e. that if the category is not found, the corrector tried to access an incorrect memory location, corrupting in irreproducible way the subsequent modules (electron ID modules, for example)

**Comment by schoef** [comment]
@emanueledimarco 
I processed almost all available mAODv2 with this branch (including f38d7ff ) and have so far not seen a failure.

**Comment by emanueledimarco** [comment]
I have also validated the scale and resolution corrections on the golden JSON with 7.65 fb-1 and they work as expected.

**Pull request merged**
