### PR TITLE
Extra photon working points, add metNoEle and bug fix for metNoX

### PR DESCRIPTION
**Pull request by aelwood**
- Added extra photon working points for Phys14 and CSA14 studies as detailed in https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2
- Fixed bug when making metNoX variables, the momentum of the object X was being subtracted from the met when it should have been added (as the met points in the opposite direction)
- Added the metNoEle variable, the met with any electron contribution subtracted
- Fixed bug in the alphaTControl region analyser

### CODE REVIEW

**Comment by mariadalfonso** [comment]
@aelwood @gpetruc 

I x-checked the content with the usual validation plots and all is fine (thanks for generalizing the photonID).

At the same time before merging, the MET analyzer should be re-adapeted after the #344 is merged since the interface is made mode generic. Once this is done a separate PR in the heppy branch is needed.

**Comment by gpetruc** [comment]
Ok now #344 is merged, can you pull the head into this branch and fix the conflicts? 
( @schoef can probably help if needed since he knows better what changed in 344 )

**Comment by aelwood** [comment]
@mariadalfonso @gpetruc I've merged the changes and sorted out the conflicts, I think I understand the changes

**Comment by mariadalfonso** [comment]
@aelwood  looks good, need to PR the Heppy files into the heppy branch

**Comment by aelwood** [comment]
@mariadalfonso heppy PR made https://github.com/CERN-PH-CMG/cmg-cmssw/pull/351

**Pull request merged**
