### PR TITLE
Heppy  jetID bugfix; PhotonBugFIX; add switch for MET recalibration and METfilter summary bit

### PR DESCRIPTION
**Pull request by mariadalfonso**

### CODE REVIEW

**Comment by aelwood** [comment]
Hi guys,

I'm getting a problem when running over some Phys14 samples - 

Traceback (most recent call last):
  File "/afs/cern.ch/user/a/aelwood/alphat/cmgtools/CMSSW_7_2_3/src/PhysicsTools/HeppyCore/python/framework/looper.py", line 245, in <module>
    looper.loop()
  File "/afs/cern.ch/user/a/aelwood/alphat/cmgtools/CMSSW_7_2_3/src/PhysicsTools/HeppyCore/python/framework/looper.py", line 167, in loop
    self.process( iEv )
  File "/afs/cern.ch/user/a/aelwood/alphat/cmgtools/CMSSW_7_2_3/src/PhysicsTools/HeppyCore/python/framework/looper.py", line 194, in process
    ret = analyzer.process( self.event )
  File "/afs/cern.ch/user/a/aelwood/alphat/cmgtools/CMSSW_7_2_3/python/PhysicsTools/Heppy/analyzers/objects/JetAnalyzer.py", line 97, in process
    elif self.testJetID (jet ):
  File "/afs/cern.ch/user/a/aelwood/alphat/cmgtools/CMSSW_7_2_3/python/PhysicsTools/Heppy/analyzers/objects/JetAnalyzer.py", line 157, in testJetID
    jet.pfJetIdPassed = jet.jetID('POG_PFID_Loose')
  File "/afs/cern.ch/user/a/aelwood/alphat/cmgtools/CMSSW_7_2_3/python/PhysicsTools/Heppy/physicsobjects/Jet.py", line 47, in jetID
    raise RuntimeError, "jetID implemented only for PF Jets"
RuntimeError: jetID implemented only for PF Jets

Is this PR designed to fix this problem? If not do you know anything about it?

Cheers,
Adam

**Comment by gpetruc** [comment]
Are you trying to apply it to the fat jets?
I think those might not have the PF information inside

```
   Giovanni
```

**Comment by aelwood** [comment]
I'm only applying it to the AK4 PF jets I think. I spoke to Maria though, and we concluded it was probably a file reading issue rather than a problem in the code. After fixing a problem I was having with certificates, it seems like the problem is occurring very rarely.

Adam

**Comment by gpetruc** [comment]
Hi Maria,

This pull request alone doesn't work in CMGTools because the addition of the parameter to the metAnalyzer in our configuration is only in #200 and not here.
This is _not_ the way PRs to the CMGTools branch are supposed to be made: you should have made a PR with both sents of committs to the CMGTools branch, and a separate PR to the Heppy branch with just the Heppy commits.
For this time only I'll take care of the integration myself.

**Pull request merged**
